services:

  linkstack:
    image: linkstackorg/linkstack:latest
    container_name: linkstack
    hostname: linkstack
    environment:
#      HTTP_SERVER_NAME: "sub.dominio.com"
#      HTTPS_SERVER_NAME: "sub.dominio.com"
      SERVER_ADMIN: tu@dominio.com   
      TZ: Europe/Madrid
      PHP_MEMORY_LIMIT: "512M"
      UPLOAD_MAX_FILESIZE: "8M"
    ports:
      - "8099:80"
      - "8443:443"
    restart: unless-stopped
    volumes:
      - linkstack:/htdocs

volumes:
  linkstack: